$(document).ready(function () {
  // set set of score numbers for score band when map is initiated
  var map_d3 = new PresidentialMap(
    "4641215133216451166244554456135135265463336531311335644412613315234441142614255241314222436642616442114653546111512122111226343356441313624625242241352"
  );
  map_d3.hashid = "ekZRl";
  map_d3.custom_text = "";
  
  map_d3.races = {
    "01": {
      state_abbr: "NSW01",
      state_name: "LINDSAY",
      id: 1,
      au_state: "NSW",
      state_fips_code: "01",
      e_votes: "1",
    },
    "02": {
      state_abbr: "NSW03",
      state_name: "KINGSFORD SMITH",
      id: 2,
      au_state: "NSW",
      state_fips_code: "02",
      e_votes: "1",
    },
    "03": {
      state_abbr: "NSW04",
      state_name: "CALARE",
      id: 3,
      au_state: "NSW",
      state_fips_code: "03",
      e_votes: "1",
    },
    "04": {
      state_abbr: "NSW05",
      state_name: "ROBERTSON",
      id: 4,
      au_state: "NSW",
      state_fips_code: "04",
      e_votes: "1",
    },
    "05": {
      state_abbr: "NSW07",
      state_name: "COOK",
      id: 5,
      au_state: "NSW",
      state_fips_code: "05",
      e_votes: "1",
    },
    "06": {
      state_abbr: "NSW08",
      state_name: "SYDNEY",
      id: 6,
      au_state: "NSW",
      state_fips_code: "06",
      e_votes: "1",
    },
    "07": {
      state_abbr: "NSW09",
      state_name: "EDEN-MONARO",
      id: 7,
      au_state: "NSW",
      state_fips_code: "07",
      e_votes: "1",
    },
    "08": {
      state_abbr: "NSW10",
      state_name: "BANKS",
      id: 8,
      au_state: "NSW",
      state_fips_code: "08",
      e_votes: "1",
    },
    "09": {
      state_abbr: "NSW11",
      state_name: "HUGHES",
      id: 9,
      au_state: "NSW",
      state_fips_code: "09",
      e_votes: "1",
    },
    10: {
      state_abbr: "NSW12",
      state_name: "NEW ENGLAND",
      id: 10,
      au_state: "NSW",
      state_fips_code: "10",
      e_votes: "1",
    },
    11: {
      state_abbr: "NSW13",
      state_name: "WERRIWA",
      id: 11,
      au_state: "NSW",
      state_fips_code: "11",
      e_votes: "1",
    },
    12: {
      state_abbr: "NSW14",
      state_name: "LYNE",
      id: 12,
      au_state: "NSW",
      state_fips_code: "12",
      e_votes: "1",
    },
    13: {
      state_abbr: "NSW15",
      state_name: "MITCHELL",
      id: 13,
      au_state: "NSW",
      state_fips_code: "13",
      e_votes: "1",
    },
    14: {
      state_abbr: "NSW16",
      state_name: "BLAXLAND",
      id: 14,
      au_state: "NSW",
      state_fips_code: "14",
      e_votes: "1",
    },
    15: {
      state_abbr: "NSW17",
      state_name: "WARRINGAH",
      id: 15,
      au_state: "NSW",
      state_fips_code: "15",
      e_votes: "1",
    },
    16: {
      state_abbr: "NSW18",
      state_name: "BRADFIELD",
      id: 16,
      au_state: "NSW",
      state_fips_code: "16",
      e_votes: "1",
    },
    17: {
      state_abbr: "NSW19",
      state_name: "FOWLER",
      id: 17,
      au_state: "NSW",
      state_fips_code: "17",
      e_votes: "1",
    },
    18: {
      state_abbr: "NSW20",
      state_name: "HUME",
      id: 18,
      au_state: "NSW",
      state_fips_code: "18",
      e_votes: "1",
    },
    19: {
      state_abbr: "NSW21",
      state_name: "CHIFLEY",
      id: 19,
      au_state: "NSW",
      state_fips_code: "19",
      e_votes: "1",
    },
    20: {
      state_abbr: "NSW22",
      state_name: "NORTH SYDNEY",
      id: 20,
      au_state: "NSW",
      state_fips_code: "20",
      e_votes: "1",
    },
    21: {
      state_abbr: "NSW23",
      state_name: "DOBELL",
      id: 21,
      au_state: "NSW",
      state_fips_code: "21",
      e_votes: "1",
    },
    22: {
      state_abbr: "NSW24",
      state_name: "BENNELONG",
      id: 22,
      au_state: "NSW",
      state_fips_code: "22",
      e_votes: "1",
    },
    23: {
      state_abbr: "NSW26",
      state_name: "GRAYNDLER",
      id: 23,
      au_state: "NSW",
      state_fips_code: "23",
      e_votes: "1",
    },
    24: {
      state_abbr: "NSW27",
      state_name: "MACARTHUR",
      id: 24,
      au_state: "NSW",
      state_fips_code: "24",
      e_votes: "1",
    },
    25: {
      state_abbr: "NSW28",
      state_name: "FARRER",
      id: 25,
      au_state: "NSW",
      state_fips_code: "25",
      e_votes: "1",
    },
    26: {
      state_abbr: "NSW29",
      state_name: "NEWCASTLE",
      id: 26,
      au_state: "NSW",
      state_fips_code: "26",
      e_votes: "1",
    },
    27: {
      state_abbr: "NSW30",
      state_name: "GREENWAY",
      id: 27,
      au_state: "NSW",
      state_fips_code: "27",
      e_votes: "1",
    },
    28: {
      state_abbr: "NSW31",
      state_name: "BEROWRA",
      id: 28,
      au_state: "NSW",
      state_fips_code: "28",
      e_votes: "1",
    },
    29: {
      state_abbr: "NSW32",
      state_name: "COWPER",
      id: 29,
      au_state: "NSW",
      state_fips_code: "29",
      e_votes: "1",
    },
    30: {
      state_abbr: "NSW33",
      state_name: "MACQUARIE",
      id: 30,
      au_state: "NSW",
      state_fips_code: "30",
      e_votes: "1",
    },
    31: {
      state_abbr: "NSW34",
      state_name: "HUNTER",
      id: 31,
      au_state: "NSW",
      state_fips_code: "31",
      e_votes: "1",
    },
    32: {
      state_abbr: "NSW36",
      state_name: "BARTON",
      id: 32,
      au_state: "NSW",
      state_fips_code: "32",
      e_votes: "1",
    },
    33: {
      state_abbr: "NSW37",
      state_name: "CUNNINGHAM",
      id: 33,
      au_state: "NSW",
      state_fips_code: "33",
      e_votes: "1",
    },
    34: {
      state_abbr: "NSW38",
      state_name: "PARKES",
      id: 34,
      au_state: "NSW",
      state_fips_code: "34",
      e_votes: "1",
    },
    35: {
      state_abbr: "NSW39",
      state_name: "RICHMOND",
      id: 35,
      au_state: "NSW",
      state_fips_code: "35",
      e_votes: "1",
    },
    36: {
      state_abbr: "NSW41",
      state_name: "PAGE",
      id: 36,
      au_state: "NSW",
      state_fips_code: "36",
      e_votes: "1",
    },
    37: {
      state_abbr: "NSW42",
      state_name: "REID",
      id: 37,
      au_state: "NSW",
      state_fips_code: "37",
      e_votes: "1",
    },
    38: {
      state_abbr: "NSW43",
      state_name: "WATSON",
      id: 38,
      au_state: "NSW",
      state_fips_code: "38",
      e_votes: "1",
    },
    39: {
      state_abbr: "NSW44",
      state_name: "SHORTLAND",
      id: 39,
      au_state: "NSW",
      state_fips_code: "39",
      e_votes: "1",
    },
    40: {
      state_abbr: "NSW45",
      state_name: "RIVERINA",
      id: 40,
      au_state: "NSW",
      state_fips_code: "40",
      e_votes: "1",
    },
    41: {
      state_abbr: "NSW46",
      state_name: "MACKELLAR",
      id: 41,
      au_state: "NSW",
      state_fips_code: "41",
      e_votes: "1",
    },
    42: {
      state_abbr: "NSW47",
      state_name: "GILMORE",
      id: 42,
      au_state: "NSW",
      state_fips_code: "42",
      e_votes: "1",
    },
    43: {
      state_abbr: "NSW48",
      state_name: "WENTWORTH",
      id: 43,
      au_state: "NSW",
      state_fips_code: "43",
      e_votes: "1",
    },
    44: {
      state_abbr: "NSW49",
      state_name: "PARRAMATTA",
      id: 44,
      au_state: "NSW",
      state_fips_code: "44",
      e_votes: "1",
    },
    45: {
      state_abbr: "NSW50",
      state_name: "MCMAHON",
      id: 45,
      au_state: "NSW",
      state_fips_code: "45",
      e_votes: "1",
    },
    46: {
      state_abbr: "NSW51",
      state_name: "PATERSON",
      id: 46,
      au_state: "NSW",
      state_fips_code: "46",
      e_votes: "1",
    },
    47: {
      state_abbr: "NSW52",
      state_name: "WHITLAM",
      id: 47,
      au_state: "NSW",
      state_fips_code: "47",
      e_votes: "1",
    },
    48: {
      state_abbr: "QLD01",
      state_name: "WIDE BAY",
      id: 48,
      au_state: "QLD",
      state_fips_code: "48",
      e_votes: "1",
    },
    49: {
      state_abbr: "QLD02",
      state_name: "BONNER",
      id: 49,
      au_state: "QLD",
      state_fips_code: "49",
      e_votes: "1",
    },
    50: {
      state_abbr: "QLD03",
      state_name: "BOWMAN",
      id: 50,
      au_state: "QLD",
      state_fips_code: "50",
      e_votes: "1",
    },
    51: {
      state_abbr: "QLD04",
      state_name: "LONGMAN",
      id: 51,
      au_state: "QLD",
      state_fips_code: "51",
      e_votes: "1",
    },
    52: {
      state_abbr: "QLD05",
      state_name: "MCPHERSON",
      id: 52,
      au_state: "QLD",
      state_fips_code: "52",
      e_votes: "1",
    },
    53: {
      state_abbr: "QLD06",
      state_name: "KENNEDY",
      id: 53,
      au_state: "QLD",
      state_fips_code: "53",
      e_votes: "1",
    },
    54: {
      state_abbr: "QLD07",
      state_name: "OXLEY",
      id: 54,
      au_state: "QLD",
      state_fips_code: "54",
      e_votes: "1",
    },
    55: {
      state_abbr: "QLD08",
      state_name: "HINKLER",
      id: 55,
      au_state: "QLD",
      state_fips_code: "55",
      e_votes: "1",
    },
    56: {
      state_abbr: "QLD09",
      state_name: "LILLEY",
      id: 56,
      au_state: "QLD",
      state_fips_code: "56",
      e_votes: "1",
    },
    57: {
      state_abbr: "QLD10",
      state_name: "DICKSON",
      id: 57,
      au_state: "QLD",
      state_fips_code: "57",
      e_votes: "1",
    },
    58: {
      state_abbr: "QLD11",
      state_name: "RANKIN",
      id: 58,
      au_state: "QLD",
      state_fips_code: "58",
      e_votes: "1",
    },
    59: {
      state_abbr: "QLD12",
      state_name: "FLYNN",
      id: 59,
      au_state: "QLD",
      state_fips_code: "59",
      e_votes: "1",
    },
    60: {
      state_abbr: "QLD13",
      state_name: "LEICHHARDT",
      id: 60,
      au_state: "QLD",
      state_fips_code: "60",
      e_votes: "1",
    },
    61: {
      state_abbr: "QLD14",
      state_name: "RYAN",
      id: 61,
      au_state: "QLD",
      state_fips_code: "61",
      e_votes: "1",
    },
    62: {
      state_abbr: "QLD15",
      state_name: "HERBERT",
      id: 62,
      au_state: "QLD",
      state_fips_code: "62",
      e_votes: "1",
    },
    63: {
      state_abbr: "QLD16",
      state_name: "MONCRIEFF",
      id: 63,
      au_state: "QLD",
      state_fips_code: "63",
      e_votes: "1",
    },
    64: {
      state_abbr: "QLD17",
      state_name: "MORETON",
      id: 64,
      au_state: "QLD",
      state_fips_code: "64",
      e_votes: "1",
    },
    65: {
      state_abbr: "QLD18",
      state_name: "DAWSON",
      id: 65,
      au_state: "QLD",
      state_fips_code: "65",
      e_votes: "1",
    },
    66: {
      state_abbr: "QLD19",
      state_name: "BLAIR",
      id: 66,
      au_state: "QLD",
      state_fips_code: "66",
      e_votes: "1",
    },
    67: {
      state_abbr: "QLD20",
      state_name: "MARANOA",
      id: 67,
      au_state: "QLD",
      state_fips_code: "67",
      e_votes: "1",
    },
    68: {
      state_abbr: "QLD21",
      state_name: "GROOM",
      id: 68,
      au_state: "QLD",
      state_fips_code: "68",
      e_votes: "1",
    },
    69: {
      state_abbr: "QLD22",
      state_name: "PETRIE",
      id: 69,
      au_state: "QLD",
      state_fips_code: "69",
      e_votes: "1",
    },
    70: {
      state_abbr: "QLD23",
      state_name: "FORDE",
      id: 70,
      au_state: "QLD",
      state_fips_code: "70",
      e_votes: "1",
    },
    71: {
      state_abbr: "QLD24",
      state_name: "CAPRICORNIA",
      id: 71,
      au_state: "QLD",
      state_fips_code: "71",
      e_votes: "1",
    },
    72: {
      state_abbr: "QLD25",
      state_name: "BRISBANE",
      id: 72,
      au_state: "QLD",
      state_fips_code: "72",
      e_votes: "1",
    },
    73: {
      state_abbr: "QLD26",
      state_name: "FAIRFAX",
      id: 73,
      au_state: "QLD",
      state_fips_code: "73",
      e_votes: "1",
    },
    74: {
      state_abbr: "QLD27",
      state_name: "FISHER",
      id: 74,
      au_state: "QLD",
      state_fips_code: "74",
      e_votes: "1",
    },
    75: {
      state_abbr: "QLD28",
      state_name: "GRIFFITH",
      id: 75,
      au_state: "QLD",
      state_fips_code: "75",
      e_votes: "1",
    },
    76: {
      state_abbr: "QLD29",
      state_name: "FADDEN",
      id: 76,
      au_state: "QLD",
      state_fips_code: "76",
      e_votes: "1",
    },
    77: {
      state_abbr: "QLD30",
      state_name: "WRIGHT",
      id: 77,
      au_state: "QLD",
      state_fips_code: "77",
      e_votes: "1",
    },
    78: {
      state_abbr: "SA01",
      state_name: "BOOTHBY",
      id: 78,
      au_state: "SA",
      state_fips_code: "78",
      e_votes: "1",
    },
    79: {
      state_abbr: "SA02",
      state_name: "GREY",
      id: 79,
      au_state: "SA",
      state_fips_code: "79",
      e_votes: "1",
    },
    80: {
      state_abbr: "SA03",
      state_name: "STURT",
      id: 80,
      au_state: "SA",
      state_fips_code: "80",
      e_votes: "1",
    },
    81: {
      state_abbr: "SA05",
      state_name: "MAYO",
      id: 81,
      au_state: "SA",
      state_fips_code: "81",
      e_votes: "1",
    },
    82: {
      state_abbr: "SA06",
      state_name: "MAKIN",
      id: 82,
      au_state: "SA",
      state_fips_code: "82",
      e_votes: "1",
    },
    83: {
      state_abbr: "SA07",
      state_name: "HINDMARSH",
      id: 83,
      au_state: "SA",
      state_fips_code: "83",
      e_votes: "1",
    },
    84: {
      state_abbr: "SA08",
      state_name: "KINGSTON",
      id: 84,
      au_state: "SA",
      state_fips_code: "84",
      e_votes: "1",
    },
    85: {
      state_abbr: "SA10",
      state_name: "ADELAIDE",
      id: 85,
      au_state: "SA",
      state_fips_code: "85",
      e_votes: "1",
    },
    86: {
      state_abbr: "SA11",
      state_name: "BARKER",
      id: 86,
      au_state: "SA",
      state_fips_code: "86",
      e_votes: "1",
    },
    87: {
      state_abbr: "SA12",
      state_name: "SPENCE",
      id: 87,
      au_state: "SA",
      state_fips_code: "87",
      e_votes: "1",
    },
    88: {
      state_abbr: "TAS01",
      state_name: "BASS",
      id: 88,
      au_state: "TAS",
      state_fips_code: "88",
      e_votes: "1",
    },
    89: {
      state_abbr: "TAS02",
      state_name: "BRADDON",
      id: 89,
      au_state: "TAS",
      state_fips_code: "89",
      e_votes: "1",
    },
    90: {
      state_abbr: "TAS03",
      state_name: "FRANKLIN",
      id: 90,
      au_state: "TAS",
      state_fips_code: "90",
      e_votes: "1",
    },
    91: {
      state_abbr: "TAS04",
      state_name: "LYONS",
      id: 91,
      au_state: "TAS",
      state_fips_code: "91",
      e_votes: "1",
    },
    92: {
      state_abbr: "TAS06",
      state_name: "CLARK",
      id: 92,
      au_state: "TAS",
      state_fips_code: "92",
      e_votes: "1",
    },
    93: {
      state_abbr: "VIC01",
      state_name: "GIPPSLAND",
      id: 93,
      au_state: "VIC",
      state_fips_code: "93",
      e_votes: "1",
    },
    94: {
      state_abbr: "VIC02",
      state_name: "MALLEE",
      id: 94,
      au_state: "VIC",
      state_fips_code: "94",
      e_votes: "1",
    },
    95: {
      state_abbr: "VIC03",
      state_name: "ASTON",
      id: 95,
      au_state: "VIC",
      state_fips_code: "95",
      e_votes: "1",
    },
    96: {
      state_abbr: "VIC04",
      state_name: "WANNON",
      id: 96,
      au_state: "VIC",
      state_fips_code: "96",
      e_votes: "1",
    },
    97: {
      state_abbr: "VIC05",
      state_name: "HOLT",
      id: 97,
      au_state: "VIC",
      state_fips_code: "97",
      e_votes: "1",
    },
    98: {
      state_abbr: "VIC06",
      state_name: "MARIBYRNONG",
      id: 98,
      au_state: "VIC",
      state_fips_code: "98",
      e_votes: "1",
    },
    99: {
      state_abbr: "VIC07",
      state_name: "HIGGINS",
      id: 99,
      au_state: "VIC",
      state_fips_code: "99",
      e_votes: "1",
    },
    100: {
      state_abbr: "VIC08",
      state_name: "DUNKLEY",
      id: 100,
      au_state: "VIC",
      state_fips_code: "100",
      e_votes: "1",
    },
    101: {
      state_abbr: "VIC10",
      state_name: "GELLIBRAND",
      id: 101,
      au_state: "VIC",
      state_fips_code: "101",
      e_votes: "1",
    },
    102: {
      state_abbr: "VIC12",
      state_name: "MENZIES",
      id: 102,
      au_state: "VIC",
      state_fips_code: "102",
      e_votes: "1",
    },
    103: {
      state_abbr: "VIC13",
      state_name: "DEAKIN",
      id: 103,
      au_state: "VIC",
      state_fips_code: "103",
      e_votes: "1",
    },
    104: {
      state_abbr: "VIC14",
      state_name: "SCULLIN",
      id: 104,
      au_state: "VIC",
      state_fips_code: "104",
      e_votes: "1",
    },
    105: {
      state_abbr: "VIC15",
      state_name: "WILLS",
      id: 105,
      au_state: "VIC",
      state_fips_code: "105",
      e_votes: "1",
    },
    106: {
      state_abbr: "VIC17",
      state_name: "MELBOURNE",
      id: 106,
      au_state: "VIC",
      state_fips_code: "106",
      e_votes: "1",
    },
    107: {
      state_abbr: "VIC18",
      state_name: "CALWELL",
      id: 107,
      au_state: "VIC",
      state_fips_code: "107",
      e_votes: "1",
    },
    108: {
      state_abbr: "VIC19",
      state_name: "MCEWEN",
      id: 108,
      au_state: "VIC",
      state_fips_code: "108",
      e_votes: "1",
    },
    109: {
      state_abbr: "VIC20",
      state_name: "FLINDERS",
      id: 109,
      au_state: "VIC",
      state_fips_code: "109",
      e_votes: "1",
    },
    110: {
      state_abbr: "VIC21",
      state_name: "INDI",
      id: 110,
      au_state: "VIC",
      state_fips_code: "110",
      e_votes: "1",
    },
    111: {
      state_abbr: "VIC23",
      state_name: "LA TROBE",
      id: 111,
      au_state: "VIC",
      state_fips_code: "111",
      e_votes: "1",
    },
    112: {
      state_abbr: "VIC24",
      state_name: "BENDIGO",
      id: 112,
      au_state: "VIC",
      state_fips_code: "112",
      e_votes: "1",
    },
    113: {
      state_abbr: "VIC25",
      state_name: "BALLARAT",
      id: 113,
      au_state: "VIC",
      state_fips_code: "113",
      e_votes: "1",
    },
    114: {
      state_abbr: "VIC26",
      state_name: "CHISHOLM",
      id: 114,
      au_state: "VIC",
      state_fips_code: "114",
      e_votes: "1",
    },
    115: {
      state_abbr: "VIC27",
      state_name: "CORANGAMITE",
      id: 115,
      au_state: "VIC",
      state_fips_code: "115",
      e_votes: "1",
    },
    116: {
      state_abbr: "VIC28",
      state_name: "GORTON",
      id: 116,
      au_state: "VIC",
      state_fips_code: "116",
      e_votes: "1",
    },
    117: {
      state_abbr: "VIC29",
      state_name: "KOOYONG",
      id: 117,
      au_state: "VIC",
      state_fips_code: "117",
      e_votes: "1",
    },
    118: {
      state_abbr: "VIC30",
      state_name: "LALOR",
      id: 118,
      au_state: "VIC",
      state_fips_code: "118",
      e_votes: "1",
    },
    119: {
      state_abbr: "VIC31",
      state_name: "CASEY",
      id: 119,
      au_state: "VIC",
      state_fips_code: "119",
      e_votes: "1",
    },
    120: {
      state_abbr: "VIC32",
      state_name: "CORIO",
      id: 120,
      au_state: "VIC",
      state_fips_code: "120",
      e_votes: "1",
    },
    121: {
      state_abbr: "VIC33",
      state_name: "JAGAJAGA",
      id: 121,
      au_state: "VIC",
      state_fips_code: "121",
      e_votes: "1",
    },
    122: {
      state_abbr: "VIC34",
      state_name: "HOTHAM",
      id: 122,
      au_state: "VIC",
      state_fips_code: "122",
      e_votes: "1",
    },
    123: {
      state_abbr: "VIC35",
      state_name: "BRUCE",
      id: 123,
      au_state: "VIC",
      state_fips_code: "123",
      e_votes: "1",
    },
    124: {
      state_abbr: "VIC36",
      state_name: "ISAACS",
      id: 124,
      au_state: "VIC",
      state_fips_code: "124",
      e_votes: "1",
    },
    125: {
      state_abbr: "VIC37",
      state_name: "GOLDSTEIN",
      id: 125,
      au_state: "VIC",
      state_fips_code: "125",
      e_votes: "1",
    },
    126: {
      state_abbr: "VIC38",
      state_name: "MONASH",
      id: 126,
      au_state: "VIC",
      state_fips_code: "126",
      e_votes: "1",
    },
    127: {
      state_abbr: "VIC39",
      state_name: "FRASER",
      id: 127,
      au_state: "VIC",
      state_fips_code: "127",
      e_votes: "1",
    },
    128: {
      state_abbr: "VIC40",
      state_name: "COOPER",
      id: 128,
      au_state: "VIC",
      state_fips_code: "128",
      e_votes: "1",
    },
    129: {
      state_abbr: "VIC41",
      state_name: "NICHOLLS",
      id: 129,
      au_state: "VIC",
      state_fips_code: "129",
      e_votes: "1",
    },
    130: {
      state_abbr: "VIC42",
      state_name: "MACNAMARA",
      id: 130,
      au_state: "VIC",
      state_fips_code: "130",
      e_votes: "1",
    },
    131: {
      state_abbr: "WA17",
      state_name: "BRAND",
      id: 131,
      au_state: "WA",
      state_fips_code: "131",
      e_votes: "1",
    },
    132: {
      state_abbr: "WA18",
      state_name: "CANNING",
      id: 132,
      au_state: "WA",
      state_fips_code: "132",
      e_votes: "1",
    },
    133: {
      state_abbr: "WA19",
      state_name: "COWAN",
      id: 133,
      au_state: "WA",
      state_fips_code: "133",
      e_votes: "1",
    },
    134: {
      state_abbr: "WA20",
      state_name: "CURTIN",
      id: 134,
      au_state: "WA",
      state_fips_code: "134",
      e_votes: "1",
    },
    135: {
      state_abbr: "WA21",
      state_name: "DURACK",
      id: 135,
      au_state: "WA",
      state_fips_code: "135",
      e_votes: "1",
    },
    136: {
      state_abbr: "WA22",
      state_name: "FORREST",
      id: 136,
      au_state: "WA",
      state_fips_code: "136",
      e_votes: "1",
    },
    137: {
      state_abbr: "WA23",
      state_name: "FREMANTLE",
      id: 137,
      au_state: "WA",
      state_fips_code: "137",
      e_votes: "1",
    },
    138: {
      state_abbr: "WA24",
      state_name: "HASLUCK",
      id: 138,
      au_state: "WA",
      state_fips_code: "138",
      e_votes: "1",
    },
    139: {
      state_abbr: "WA25",
      state_name: "MOORE",
      id: 139,
      au_state: "WA",
      state_fips_code: "139",
      e_votes: "1",
    },
    140: {
      state_abbr: "WA26",
      state_name: "BURT",
      id: 140,
      au_state: "WA",
      state_fips_code: "140",
      e_votes: "1",
    },
    141: {
      state_abbr: "WA27",
      state_name: "O'CONNOR",
      id: 141,
      au_state: "WA",
      state_fips_code: "141",
      e_votes: "1",
    },
    142: {
      state_abbr: "WA28",
      state_name: "PEARCE",
      id: 142,
      au_state: "WA",
      state_fips_code: "142",
      e_votes: "1",
    },
    143: {
      state_abbr: "WA29",
      state_name: "PERTH",
      id: 143,
      au_state: "WA",
      state_fips_code: "143",
      e_votes: "1",
    },
    144: {
      state_abbr: "WA30",
      state_name: "STIRLING",
      id: 144,
      au_state: "WA",
      state_fips_code: "144",
      e_votes: "1",
    },
    145: {
      state_abbr: "WA31",
      state_name: "SWAN",
      id: 145,
      au_state: "WA",
      state_fips_code: "145",
      e_votes: "1",
    },
    146: {
      state_abbr: "WA32",
      state_name: "TANGNEY",
      id: 146,
      au_state: "WA",
      state_fips_code: "146",
      e_votes: "1",
    },
    147: {
      state_abbr: "ACT03",
      state_name: "CANBERRA",
      id: 147,
      au_state: "ACT",
      state_fips_code: "147",
      e_votes: "1",
    },
    148: {
      state_abbr: "ACT04",
      state_name: "FENNER",
      id: 148,
      au_state: "ACT",
      state_fips_code: "148",
      e_votes: "1",
    },
    149: {
      state_abbr: "ACT05",
      state_name: "BEAN",
      id: 149,
      au_state: "ACT",
      state_fips_code: "149",
      e_votes: "1",
    },
    150: {
      state_abbr: "NT04",
      state_name: "LINGIARI",
      id: 150,
      au_state: "NT",
      state_fips_code: "150",
      e_votes: "1",
    },
    151: {
      state_abbr: "NT05",
      state_name: "SOLOMON",
      id: 151,
      au_state: "NT",
      state_fips_code: "151",
      e_votes: "1",
    },
  };


  map_d3.seats = {
    "01": [
      {
        state_abbr: "NSW01",
        state_name: "LINDSAY",
        id: 1,
        au_state: "NSW",
        state_fips_code: "01",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "02": [
      {
        state_abbr: "NSW03",
        state_name: "KINGSFORD SMITH",
        id: 2,
        au_state: "NSW",
        state_fips_code: "02",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "03": [
      {
        state_abbr: "NSW04",
        state_name: "CALARE",
        id: 3,
        au_state: "NSW",
        state_fips_code: "03",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "04": [
      {
        state_abbr: "NSW05",
        state_name: "ROBERTSON",
        id: 4,
        au_state: "NSW",
        state_fips_code: "04",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "05": [
      {
        state_abbr: "NSW07",
        state_name: "COOK",
        id: 5,
        au_state: "NSW",
        state_fips_code: "05",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "06": [
      {
        state_abbr: "NSW08",
        state_name: "SYDNEY",
        id: 6,
        au_state: "NSW",
        state_fips_code: "06",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "07": [
      {
        state_abbr: "NSW09",
        state_name: "EDEN-MONARO",
        id: 7,
        au_state: "NSW",
        state_fips_code: "07",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "08": [
      {
        state_abbr: "NSW10",
        state_name: "BANKS",
        id: 8,
        au_state: "NSW",
        state_fips_code: "08",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    "09": [
      {
        state_abbr: "NSW11",
        state_name: "HUGHES",
        id: 9,
        au_state: "NSW",
        state_fips_code: "09",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    10: [
      {
        state_abbr: "NSW12",
        state_name: "NEW ENGLAND",
        id: 10,
        au_state: "NSW",
        state_fips_code: "10",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    11: [
      {
        state_abbr: "NSW13",
        state_name: "WERRIWA",
        id: 11,
        au_state: "NSW",
        state_fips_code: "11",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    12: [
      {
        state_abbr: "NSW14",
        state_name: "LYNE",
        id: 12,
        au_state: "NSW",
        state_fips_code: "12",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    13: [
      {
        state_abbr: "NSW15",
        state_name: "MITCHELL",
        id: 13,
        au_state: "NSW",
        state_fips_code: "13",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    14: [
      {
        state_abbr: "NSW16",
        state_name: "BLAXLAND",
        id: 14,
        au_state: "NSW",
        state_fips_code: "14",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    15: [
      {
        state_abbr: "NSW17",
        state_name: "WARRINGAH",
        id: 15,
        au_state: "NSW",
        state_fips_code: "15",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    16: [
      {
        state_abbr: "NSW18",
        state_name: "BRADFIELD",
        id: 16,
        au_state: "NSW",
        state_fips_code: "16",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    17: [
      {
        state_abbr: "NSW19",
        state_name: "FOWLER",
        id: 17,
        au_state: "NSW",
        state_fips_code: "17",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    18: [
      {
        state_abbr: "NSW20",
        state_name: "HUME",
        id: 18,
        au_state: "NSW",
        state_fips_code: "18",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    19: [
      {
        state_abbr: "NSW21",
        state_name: "CHIFLEY",
        id: 19,
        au_state: "NSW",
        state_fips_code: "19",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    20: [
      {
        state_abbr: "NSW22",
        state_name: "NORTH SYDNEY",
        id: 20,
        au_state: "NSW",
        state_fips_code: "20",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    21: [
      {
        state_abbr: "NSW23",
        state_name: "DOBELL",
        id: 21,
        au_state: "NSW",
        state_fips_code: "21",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    22: [
      {
        state_abbr: "NSW24",
        state_name: "BENNELONG",
        id: 22,
        au_state: "NSW",
        state_fips_code: "22",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    23: [
      {
        state_abbr: "NSW26",
        state_name: "GRAYNDLER",
        id: 23,
        au_state: "NSW",
        state_fips_code: "23",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    24: [
      {
        state_abbr: "NSW27",
        state_name: "MACARTHUR",
        id: 24,
        au_state: "NSW",
        state_fips_code: "24",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    25: [
      {
        state_abbr: "NSW28",
        state_name: "FARRER",
        id: 25,
        au_state: "NSW",
        state_fips_code: "25",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    26: [
      {
        state_abbr: "NSW29",
        state_name: "NEWCASTLE",
        id: 26,
        au_state: "NSW",
        state_fips_code: "26",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    27: [
      {
        state_abbr: "NSW30",
        state_name: "GREENWAY",
        id: 27,
        au_state: "NSW",
        state_fips_code: "27",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    28: [
      {
        state_abbr: "NSW31",
        state_name: "BEROWRA",
        id: 28,
        au_state: "NSW",
        state_fips_code: "28",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    29: [
      {
        state_abbr: "NSW32",
        state_name: "COWPER",
        id: 29,
        au_state: "NSW",
        state_fips_code: "29",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    30: [
      {
        state_abbr: "NSW33",
        state_name: "MACQUARIE",
        id: 30,
        au_state: "NSW",
        state_fips_code: "30",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    31: [
      {
        state_abbr: "NSW34",
        state_name: "HUNTER",
        id: 31,
        au_state: "NSW",
        state_fips_code: "31",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    32: [
      {
        state_abbr: "NSW36",
        state_name: "BARTON",
        id: 32,
        au_state: "NSW",
        state_fips_code: "32",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    33: [
      {
        state_abbr: "NSW37",
        state_name: "CUNNINGHAM",
        id: 33,
        au_state: "NSW",
        state_fips_code: "33",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    34: [
      {
        state_abbr: "NSW38",
        state_name: "PARKES",
        id: 34,
        au_state: "NSW",
        state_fips_code: "34",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    35: [
      {
        state_abbr: "NSW39",
        state_name: "RICHMOND",
        id: 35,
        au_state: "NSW",
        state_fips_code: "35",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    36: [
      {
        state_abbr: "NSW41",
        state_name: "PAGE",
        id: 36,
        au_state: "NSW",
        state_fips_code: "36",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    37: [
      {
        state_abbr: "NSW42",
        state_name: "REID",
        id: 37,
        au_state: "NSW",
        state_fips_code: "37",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    38: [
      {
        state_abbr: "NSW43",
        state_name: "WATSON",
        id: 38,
        au_state: "NSW",
        state_fips_code: "38",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    39: [
      {
        state_abbr: "NSW44",
        state_name: "SHORTLAND",
        id: 39,
        au_state: "NSW",
        state_fips_code: "39",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    40: [
      {
        state_abbr: "NSW45",
        state_name: "RIVERINA",
        id: 40,
        au_state: "NSW",
        state_fips_code: "40",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    41: [
      {
        state_abbr: "NSW46",
        state_name: "MACKELLAR",
        id: 41,
        au_state: "NSW",
        state_fips_code: "41",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    42: [
      {
        state_abbr: "NSW47",
        state_name: "GILMORE",
        id: 42,
        au_state: "NSW",
        state_fips_code: "42",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    43: [
      {
        state_abbr: "NSW48",
        state_name: "WENTWORTH",
        id: 43,
        au_state: "NSW",
        state_fips_code: "43",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    44: [
      {
        state_abbr: "NSW49",
        state_name: "PARRAMATTA",
        id: 44,
        au_state: "NSW",
        state_fips_code: "44",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    45: [
      {
        state_abbr: "NSW50",
        state_name: "MCMAHON",
        id: 45,
        au_state: "NSW",
        state_fips_code: "45",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    46: [
      {
        state_abbr: "NSW51",
        state_name: "PATERSON",
        id: 46,
        au_state: "NSW",
        state_fips_code: "46",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    47: [
      {
        state_abbr: "NSW52",
        state_name: "WHITLAM",
        id: 47,
        au_state: "NSW",
        state_fips_code: "47",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    48: [
      {
        state_abbr: "QLD01",
        state_name: "WIDE BAY",
        id: 48,
        au_state: "QLD",
        state_fips_code: "48",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    49: [
      {
        state_abbr: "QLD02",
        state_name: "BONNER",
        id: 49,
        au_state: "QLD",
        state_fips_code: "49",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    50: [
      {
        state_abbr: "QLD03",
        state_name: "BOWMAN",
        id: 50,
        au_state: "QLD",
        state_fips_code: "50",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    51: [
      {
        state_abbr: "QLD04",
        state_name: "LONGMAN",
        id: 51,
        au_state: "QLD",
        state_fips_code: "51",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    52: [
      {
        state_abbr: "QLD05",
        state_name: "MCPHERSON",
        id: 52,
        au_state: "QLD",
        state_fips_code: "52",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    53: [
      {
        state_abbr: "QLD06",
        state_name: "KENNEDY",
        id: 53,
        au_state: "QLD",
        state_fips_code: "53",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    54: [
      {
        state_abbr: "QLD07",
        state_name: "OXLEY",
        id: 54,
        au_state: "QLD",
        state_fips_code: "54",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    55: [
      {
        state_abbr: "QLD08",
        state_name: "HINKLER",
        id: 55,
        au_state: "QLD",
        state_fips_code: "55",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    56: [
      {
        state_abbr: "QLD09",
        state_name: "LILLEY",
        id: 56,
        au_state: "QLD",
        state_fips_code: "56",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    57: [
      {
        state_abbr: "QLD10",
        state_name: "DICKSON",
        id: 57,
        au_state: "QLD",
        state_fips_code: "57",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    58: [
      {
        state_abbr: "QLD11",
        state_name: "RANKIN",
        id: 58,
        au_state: "QLD",
        state_fips_code: "58",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    59: [
      {
        state_abbr: "QLD12",
        state_name: "FLYNN",
        id: 59,
        au_state: "QLD",
        state_fips_code: "59",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    60: [
      {
        state_abbr: "QLD13",
        state_name: "LEICHHARDT",
        id: 60,
        au_state: "QLD",
        state_fips_code: "60",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    61: [
      {
        state_abbr: "QLD14",
        state_name: "RYAN",
        id: 61,
        au_state: "QLD",
        state_fips_code: "61",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    62: [
      {
        state_abbr: "QLD15",
        state_name: "HERBERT",
        id: 62,
        au_state: "QLD",
        state_fips_code: "62",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    63: [
      {
        state_abbr: "QLD16",
        state_name: "MONCRIEFF",
        id: 63,
        au_state: "QLD",
        state_fips_code: "63",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    64: [
      {
        state_abbr: "QLD17",
        state_name: "MORETON",
        id: 64,
        au_state: "QLD",
        state_fips_code: "64",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    65: [
      {
        state_abbr: "QLD18",
        state_name: "DAWSON",
        id: 65,
        au_state: "QLD",
        state_fips_code: "65",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    66: [
      {
        state_abbr: "QLD19",
        state_name: "BLAIR",
        id: 66,
        au_state: "QLD",
        state_fips_code: "66",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    67: [
      {
        state_abbr: "QLD20",
        state_name: "MARANOA",
        id: 67,
        au_state: "QLD",
        state_fips_code: "67",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    68: [
      {
        state_abbr: "QLD21",
        state_name: "GROOM",
        id: 68,
        au_state: "QLD",
        state_fips_code: "68",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    69: [
      {
        state_abbr: "QLD22",
        state_name: "PETRIE",
        id: 69,
        au_state: "QLD",
        state_fips_code: "69",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    70: [
      {
        state_abbr: "QLD23",
        state_name: "FORDE",
        id: 70,
        au_state: "QLD",
        state_fips_code: "70",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    71: [
      {
        state_abbr: "QLD24",
        state_name: "CAPRICORNIA",
        id: 71,
        au_state: "QLD",
        state_fips_code: "71",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    72: [
      {
        state_abbr: "QLD25",
        state_name: "BRISBANE",
        id: 72,
        au_state: "QLD",
        state_fips_code: "72",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    73: [
      {
        state_abbr: "QLD26",
        state_name: "FAIRFAX",
        id: 73,
        au_state: "QLD",
        state_fips_code: "73",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    74: [
      {
        state_abbr: "QLD27",
        state_name: "FISHER",
        id: 74,
        au_state: "QLD",
        state_fips_code: "74",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    75: [
      {
        state_abbr: "QLD28",
        state_name: "GRIFFITH",
        id: 75,
        au_state: "QLD",
        state_fips_code: "75",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    76: [
      {
        state_abbr: "QLD29",
        state_name: "FADDEN",
        id: 76,
        au_state: "QLD",
        state_fips_code: "76",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    77: [
      {
        state_abbr: "QLD30",
        state_name: "WRIGHT",
        id: 77,
        au_state: "QLD",
        state_fips_code: "77",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    78: [
      {
        state_abbr: "SA01",
        state_name: "BOOTHBY",
        id: 78,
        au_state: "SA",
        state_fips_code: "78",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    79: [
      {
        state_abbr: "SA02",
        state_name: "GREY",
        id: 79,
        au_state: "SA",
        state_fips_code: "79",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    80: [
      {
        state_abbr: "SA03",
        state_name: "STURT",
        id: 80,
        au_state: "SA",
        state_fips_code: "80",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    81: [
      {
        state_abbr: "SA05",
        state_name: "MAYO",
        id: 81,
        au_state: "SA",
        state_fips_code: "81",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    82: [
      {
        state_abbr: "SA06",
        state_name: "MAKIN",
        id: 82,
        au_state: "SA",
        state_fips_code: "82",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    83: [
      {
        state_abbr: "SA07",
        state_name: "HINDMARSH",
        id: 83,
        au_state: "SA",
        state_fips_code: "83",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    84: [
      {
        state_abbr: "SA08",
        state_name: "KINGSTON",
        id: 84,
        au_state: "SA",
        state_fips_code: "84",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    85: [
      {
        state_abbr: "SA10",
        state_name: "ADELAIDE",
        id: 85,
        au_state: "SA",
        state_fips_code: "85",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    86: [
      {
        state_abbr: "SA11",
        state_name: "BARKER",
        id: 86,
        au_state: "SA",
        state_fips_code: "86",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    87: [
      {
        state_abbr: "SA12",
        state_name: "SPENCE",
        id: 87,
        au_state: "SA",
        state_fips_code: "87",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    88: [
      {
        state_abbr: "TAS01",
        state_name: "BASS",
        id: 88,
        au_state: "TAS",
        state_fips_code: "88",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    89: [
      {
        state_abbr: "TAS02",
        state_name: "BRADDON",
        id: 89,
        au_state: "TAS",
        state_fips_code: "89",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    90: [
      {
        state_abbr: "TAS03",
        state_name: "FRANKLIN",
        id: 90,
        au_state: "TAS",
        state_fips_code: "90",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    91: [
      {
        state_abbr: "TAS04",
        state_name: "LYONS",
        id: 91,
        au_state: "TAS",
        state_fips_code: "91",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    92: [
      {
        state_abbr: "TAS06",
        state_name: "CLARK",
        id: 92,
        au_state: "TAS",
        state_fips_code: "92",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    93: [
      {
        state_abbr: "VIC01",
        state_name: "GIPPSLAND",
        id: 93,
        au_state: "VIC",
        state_fips_code: "93",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    94: [
      {
        state_abbr: "VIC02",
        state_name: "MALLEE",
        id: 94,
        au_state: "VIC",
        state_fips_code: "94",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    95: [
      {
        state_abbr: "VIC03",
        state_name: "ASTON",
        id: 95,
        au_state: "VIC",
        state_fips_code: "95",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    96: [
      {
        state_abbr: "VIC04",
        state_name: "WANNON",
        id: 96,
        au_state: "VIC",
        state_fips_code: "96",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    97: [
      {
        state_abbr: "VIC05",
        state_name: "HOLT",
        id: 97,
        au_state: "VIC",
        state_fips_code: "97",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    98: [
      {
        state_abbr: "VIC06",
        state_name: "MARIBYRNONG",
        id: 98,
        au_state: "VIC",
        state_fips_code: "98",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    99: [
      {
        state_abbr: "VIC07",
        state_name: "HIGGINS",
        id: 99,
        au_state: "VIC",
        state_fips_code: "99",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    100: [
      {
        state_abbr: "VIC08",
        state_name: "DUNKLEY",
        id: 100,
        au_state: "VIC",
        state_fips_code: "100",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    101: [
      {
        state_abbr: "VIC10",
        state_name: "GELLIBRAND",
        id: 101,
        au_state: "VIC",
        state_fips_code: "101",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    102: [
      {
        state_abbr: "VIC12",
        state_name: "MENZIES",
        id: 102,
        au_state: "VIC",
        state_fips_code: "102",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    103: [
      {
        state_abbr: "VIC13",
        state_name: "DEAKIN",
        id: 103,
        au_state: "VIC",
        state_fips_code: "103",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    104: [
      {
        state_abbr: "VIC14",
        state_name: "SCULLIN",
        id: 104,
        au_state: "VIC",
        state_fips_code: "104",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    105: [
      {
        state_abbr: "VIC15",
        state_name: "WILLS",
        id: 105,
        au_state: "VIC",
        state_fips_code: "105",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    106: [
      {
        state_abbr: "VIC17",
        state_name: "MELBOURNE",
        id: 106,
        au_state: "VIC",
        state_fips_code: "106",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    107: [
      {
        state_abbr: "VIC18",
        state_name: "CALWELL",
        id: 107,
        au_state: "VIC",
        state_fips_code: "107",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    108: [
      {
        state_abbr: "VIC19",
        state_name: "MCEWEN",
        id: 108,
        au_state: "VIC",
        state_fips_code: "108",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    109: [
      {
        state_abbr: "VIC20",
        state_name: "FLINDERS",
        id: 109,
        au_state: "VIC",
        state_fips_code: "109",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    110: [
      {
        state_abbr: "VIC21",
        state_name: "INDI",
        id: 110,
        au_state: "VIC",
        state_fips_code: "110",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    111: [
      {
        state_abbr: "VIC23",
        state_name: "LA TROBE",
        id: 111,
        au_state: "VIC",
        state_fips_code: "111",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    112: [
      {
        state_abbr: "VIC24",
        state_name: "BENDIGO",
        id: 112,
        au_state: "VIC",
        state_fips_code: "112",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    113: [
      {
        state_abbr: "VIC25",
        state_name: "BALLARAT",
        id: 113,
        au_state: "VIC",
        state_fips_code: "113",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    114: [
      {
        state_abbr: "VIC26",
        state_name: "CHISHOLM",
        id: 114,
        au_state: "VIC",
        state_fips_code: "114",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    115: [
      {
        state_abbr: "VIC27",
        state_name: "CORANGAMITE",
        id: 115,
        au_state: "VIC",
        state_fips_code: "115",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    116: [
      {
        state_abbr: "VIC28",
        state_name: "GORTON",
        id: 116,
        au_state: "VIC",
        state_fips_code: "116",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    117: [
      {
        state_abbr: "VIC29",
        state_name: "KOOYONG",
        id: 117,
        au_state: "VIC",
        state_fips_code: "117",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    118: [
      {
        state_abbr: "VIC30",
        state_name: "LALOR",
        id: 118,
        au_state: "VIC",
        state_fips_code: "118",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    119: [
      {
        state_abbr: "VIC31",
        state_name: "CASEY",
        id: 119,
        au_state: "VIC",
        state_fips_code: "119",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    120: [
      {
        state_abbr: "VIC32",
        state_name: "CORIO",
        id: 120,
        au_state: "VIC",
        state_fips_code: "120",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    121: [
      {
        state_abbr: "VIC33",
        state_name: "JAGAJAGA",
        id: 121,
        au_state: "VIC",
        state_fips_code: "121",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    122: [
      {
        state_abbr: "VIC34",
        state_name: "HOTHAM",
        id: 122,
        au_state: "VIC",
        state_fips_code: "122",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    123: [
      {
        state_abbr: "VIC35",
        state_name: "BRUCE",
        id: 123,
        au_state: "VIC",
        state_fips_code: "123",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    124: [
      {
        state_abbr: "VIC36",
        state_name: "ISAACS",
        id: 124,
        au_state: "VIC",
        state_fips_code: "124",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    125: [
      {
        state_abbr: "VIC37",
        state_name: "GOLDSTEIN",
        id: 125,
        au_state: "VIC",
        state_fips_code: "125",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    126: [
      {
        state_abbr: "VIC38",
        state_name: "MONASH",
        id: 126,
        au_state: "VIC",
        state_fips_code: "126",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    127: [
      {
        state_abbr: "VIC39",
        state_name: "FRASER",
        id: 127,
        au_state: "VIC",
        state_fips_code: "127",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    128: [
      {
        state_abbr: "VIC40",
        state_name: "COOPER",
        id: 128,
        au_state: "VIC",
        state_fips_code: "128",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    129: [
      {
        state_abbr: "VIC41",
        state_name: "NICHOLLS",
        id: 129,
        au_state: "VIC",
        state_fips_code: "129",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    130: [
      {
        state_abbr: "VIC42",
        state_name: "MACNAMARA",
        id: 130,
        au_state: "VIC",
        state_fips_code: "130",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    131: [
      {
        state_abbr: "WA17",
        state_name: "BRAND",
        id: 131,
        au_state: "WA",
        state_fips_code: "131",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    132: [
      {
        state_abbr: "WA18",
        state_name: "CANNING",
        id: 132,
        au_state: "WA",
        state_fips_code: "132",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    133: [
      {
        state_abbr: "WA19",
        state_name: "COWAN",
        id: 133,
        au_state: "WA",
        state_fips_code: "133",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    134: [
      {
        state_abbr: "WA20",
        state_name: "CURTIN",
        id: 134,
        au_state: "WA",
        state_fips_code: "134",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    135: [
      {
        state_abbr: "WA21",
        state_name: "DURACK",
        id: 135,
        au_state: "WA",
        state_fips_code: "135",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    136: [
      {
        state_abbr: "WA22",
        state_name: "FORREST",
        id: 136,
        au_state: "WA",
        state_fips_code: "136",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    137: [
      {
        state_abbr: "WA23",
        state_name: "FREMANTLE",
        id: 137,
        au_state: "WA",
        state_fips_code: "137",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    138: [
      {
        state_abbr: "WA24",
        state_name: "HASLUCK",
        id: 138,
        au_state: "WA",
        state_fips_code: "138",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    139: [
      {
        state_abbr: "WA25",
        state_name: "MOORE",
        id: 139,
        au_state: "WA",
        state_fips_code: "139",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    140: [
      {
        state_abbr: "WA26",
        state_name: "BURT",
        id: 140,
        au_state: "WA",
        state_fips_code: "140",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    141: [
      {
        state_abbr: "WA27",
        state_name: "O'CONNOR",
        id: 141,
        au_state: "WA",
        state_fips_code: "141",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    142: [
      {
        state_abbr: "WA28",
        state_name: "PEARCE",
        id: 142,
        au_state: "WA",
        state_fips_code: "142",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    143: [
      {
        state_abbr: "WA29",
        state_name: "PERTH",
        id: 143,
        au_state: "WA",
        state_fips_code: "143",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    144: [
      {
        state_abbr: "WA30",
        state_name: "STIRLING",
        id: 144,
        au_state: "WA",
        state_fips_code: "144",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    145: [
      {
        state_abbr: "WA31",
        state_name: "SWAN",
        id: 145,
        au_state: "WA",
        state_fips_code: "145",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    146: [
      {
        state_abbr: "WA32",
        state_name: "TANGNEY",
        id: 146,
        au_state: "WA",
        state_fips_code: "146",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    147: [
      {
        state_abbr: "ACT03",
        state_name: "CANBERRA",
        id: 147,
        au_state: "ACT",
        state_fips_code: "147",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    148: [
      {
        state_abbr: "ACT04",
        state_name: "FENNER",
        id: 148,
        au_state: "ACT",
        state_fips_code: "148",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    149: [
      {
        state_abbr: "ACT05",
        state_name: "BEAN",
        id: 149,
        au_state: "ACT",
        state_fips_code: "149",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    150: [
      {
        state_abbr: "NT04",
        state_name: "LINGIARI",
        id: 150,
        au_state: "NT",
        state_fips_code: "150",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
    151: [
      {
        state_abbr: "NT05",
        state_name: "SOLOMON",
        id: 151,
        au_state: "NT",
        state_fips_code: "151",
        e_votes: "1",
        pro_status: "R3",
        map_code: "4",
        special_election: false,
      },
    ],
  };

  map_d3.i_tallied_with = "I";
  map_d3.views = {
    ekZRl: {
      name: "Random Test Results",
      hashid: "ekZRl",
      description: "Random Test Results",
      map_string: "4641215133216451166244554456135135265463336531311335644412613315234441142614255241314222436642616442114653546111512122111226343356441313624625242241352",
    },
    yVDkk: {
      name: "Blank Map",
      hashid: "yVDkk",
      description: "Blank Map",
      map_string: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    },
  };
  map_d3.map_string_cookie_name = "presidential_map_string";
  map_d3.color_mode_cookie_name = "presidential_color_mode";
  map_d3.cookie_path = "/";
  map_d3.init();
});
